// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvpmyosbuxcqjfmbhtvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12cG15b3NidXhjcWpmbWJodHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDY4MDUsImV4cCI6MjA3MDU4MjgwNX0.FlAT5FJpoEIkruHfWx_FqSGHYDRHf-GrxAUnQFgyM7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});