// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufobuvtcuqntrikqlikd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmb2J1dnRjdXFudHJpa3FsaWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTczMDcsImV4cCI6MjA2ODM5MzMwN30.Id61_Mxl1g0Fm1AUsoVB6iG3gYgRkgAbgNSZhfGDwnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});